version: "3"

networks:
  front-tier:
  back-tier:

services:
  quizon-db:
    image: postgres:latest
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_PASSWORD: "postgrespw"
    ports:
      - "5432:5432"
    networks:
      - back-tier
    restart: always

  quizon-app:
    depends_on:
      - quizon-db
    build:
      context: .
      dockerfile: ./build/Dockerfile
    ports:
      - "8000:8000"
    networks:
      - back-tier

volumes:
  database_data:
    driver: local
